name: Node CI

on: 
  - push
  - pull_request

jobs:
  lint:
    runs-on: macos-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps: 
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install
        run: make install
        env:
          CI: true
      - name: lint
        run: make lint
      - name: test // code coverage
        uses: paambaati/codeclimate-action@v2.7.4
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: make test-coverage
          debug: true